# Random forest implementation

In [1]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [2]:
df = pd.read_csv('Travel.csv')
df

,CustomerID,ProdTaken,Age,TypeofContact,CityTier,DurationOfPitch,Occupation,Gender,NumberOfPersonVisiting,NumberOfFollowups,ProductPitched,PreferredPropertyStar,MaritalStatus,NumberOfTrips,Passport,PitchSatisfactionScore,OwnCar,NumberOfChildrenVisiting,Designation,MonthlyIncome
0,200000,1,41.0,Self Enquiry,3,6.0,Salaried,Female,3,3.0,Deluxe,3.0,Single,1.0,1,2,1,0.0,Manager,20993.0
1,200001,0,49.0,Company Invited,1,14.0,Salaried,Male,3,4.0,Deluxe,4.0,Divorced,2.0,0,3,1,2.0,Manager,20130.0
2,200002,1,37.0,Self Enquiry,1,8.0,Free Lancer,Male,3,4.0,Basic,3.0,Single,7.0,1,3,0,0.0,Executive,17090.0
3,200003,0,33.0,Company Invited,1,9.0,Salaried,Female,2,3.0,Basic,3.0,Divorced,2.0,1,5,1,1.0,Executive,17909.0
4,200004,0,NaN,Self Enquiry,1,8.0,Small Business,Male,2,3.0,Basic,4.0,Divorced,1.0,0,5,1,0.0,Executive,18468.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4883,204883,1,49.0,Self Enquiry,3,9.0,Small Business,Male,3,5.0,Deluxe,4.0,Unmarried,2.0,1,1,1,1.0,Manager,26576.0
4884,204884,1,28.0,Company Invited,1,31.0,Salaried,Male,4,5.0,Basic,3.0,Single,3.0,1,3,1,2.0,Executive,21212.0
4885,204885,1,52.0,Self Enquiry,3,17.0,Salaried,Female,4,4.0,Standard,4.0,Married,7.0,0,1,1,3.0,Senior Manager,31820.0
4886,204886,1,19.0,Self Enquiry,3,16.0,Small Business,Male,3,4.0,Basic,3.0,Single,3.0,0,5,0,2.0,Executive,20289.0
4887,204887,1,36.0,Self Enquiry,1,14.0,Salaried,Male,4,4.0,Basic,4.0,Unmarried,3.0,1,3,1,2.0,Executive,24041.0

In [3]:
df.isnull

<bound method DataFrame.isnull of       CustomerID  ProdTaken   Age    TypeofContact  CityTier  DurationOfPitch  \
0         200000          1  41.0     Self Enquiry         3              6.0
1         200001          0  49.0  Company Invited         1             14.0
2         200002          1  37.0     Self Enquiry         1              8.0
3         200003          0  33.0  Company Invited         1              9.0
4         200004          0   NaN     Self Enquiry         1              8.0
...          ...        ...   ...              ...       ...              ...
4883      204883          1  49.0     Self Enquiry         3              9.0
4884      204884          1  28.0  Company Invited         1             31.0
4885      204885          1  52.0     Self Enquiry         3             17.0
4886      204886          1  19.0     Self Enquiry         3             16.0
4887      204887          1  36.0     Self Enquiry         1             14.0

          Occupation  Gender  NumberOfPersonVisiting  NumberOfFollowups  \
0           Salaried  Female                       3                3.0
1           Salaried    Male                       3                4.0
2        Free Lancer    Male                       3                4.0
3           Salaried  Female                       2                3.0
4     Small Business    Male                       2                3.0
...              ...     ...                     ...                ...
4883  Small Business    Male                       3                5.0
4884        Salaried    Male                       4                5.0
4885        Salaried  Female                       4                4.0
4886  Small Business    Male                       3                4.0
4887        Salaried    Male                       4                4.0

     ProductPitched  PreferredPropertyStar MaritalStatus  NumberOfTrips  \
0            Deluxe                    3.0        Single            1.0
1            Deluxe                    4.0      Divorced            2.0
2             Basic                    3.0        Single            7.0
3             Basic                    3.0      Divorced            2.0
4             Basic                    4.0      Divorced            1.0
...             ...                    ...           ...            ...
4883         Deluxe                    4.0     Unmarried            2.0
4884          Basic                    3.0        Single            3.0
4885       Standard                    4.0       Married            7.0
4886          Basic                    3.0        Single            3.0
4887          Basic                    4.0     Unmarried            3.0

      Passport  PitchSatisfactionScore  OwnCar  NumberOfChildrenVisiting  \
0            1                       2       1                       0.0
1            0                       3       1                       2.0
2            1                       3       0                       0.0
3            1                       5       1                       1.0
4            0                       5       1                       0.0
...        ...                     ...     ...                       ...
4883         1                       1       1                       1.0
4884         1                       3       1                       2.0
4885         0                       1       1                       3.0
4886         0                       5       0                       2.0
4887         1                       3       1                       2.0

         Designation  MonthlyIncome
0            Manager        20993.0
1            Manager        20130.0
2          Executive        17090.0
3          Executive        17909.0
4          Executive        18468.0
...              ...            ...
4883         Manager        26576.0
4884       Executive        21212.0
4885  Senior Manager        31820.0
4886       Executive        20289.0
4887       Executive        24041.0

[4888 rows x 20 columns]>

In [4]:
df.isnull().sum()

CustomerID                    0
ProdTaken                     0
Age                         226
TypeofContact                25
CityTier                      0
DurationOfPitch             251
Occupation                    0
Gender                        0
NumberOfPersonVisiting        0
NumberOfFollowups            45
ProductPitched                0
PreferredPropertyStar        26
MaritalStatus                 0
NumberOfTrips               140
Passport                      0
PitchSatisfactionScore        0
OwnCar                        0
NumberOfChildrenVisiting     66
Designation                   0
MonthlyIncome               233
dtype: int64

In [5]:
df.columns

Index(['CustomerID', 'ProdTaken', 'Age', 'TypeofContact', 'CityTier',
       'DurationOfPitch', 'Occupation', 'Gender', 'NumberOfPersonVisiting',
       'NumberOfFollowups', 'ProductPitched', 'PreferredPropertyStar',
       'MaritalStatus', 'NumberOfTrips', 'Passport', 'PitchSatisfactionScore',
       'OwnCar', 'NumberOfChildrenVisiting', 'Designation', 'MonthlyIncome'],
      dtype='object')

In [6]:
df['Gender'].value_counts()

Gender
Male       2916
Female     1817
Fe Male     155
Name: count, dtype: int64

In [7]:
df['MaritalStatus'].value_counts()

MaritalStatus
Married      2340
Divorced      950
Single        916
Unmarried     682
Name: count, dtype: int64

In [8]:
df['TypeofContact'].value_counts()

TypeofContact
Self Enquiry       3444
Company Invited    1419
Name: count, dtype: int64

combine ummaried and single

In [9]:
df['Gender'] = df['Gender'].replace('Fe Male' , 'Female')

In [10]:
df['Gender'].value_counts()

Gender
Male      2916
Female    1972
Name: count, dtype: int64

In [11]:
df['MaritalStatus'] = df['MaritalStatus'].replace( 'Single' , 'Unmarried' )

In [12]:
df.head()

,CustomerID,ProdTaken,Age,TypeofContact,CityTier,DurationOfPitch,Occupation,Gender,NumberOfPersonVisiting,NumberOfFollowups,ProductPitched,PreferredPropertyStar,MaritalStatus,NumberOfTrips,Passport,PitchSatisfactionScore,OwnCar,NumberOfChildrenVisiting,Designation,MonthlyIncome
0,200000,1,41.0,Self Enquiry,3,6.0,Salaried,Female,3,3.0,Deluxe,3.0,Unmarried,1.0,1,2,1,0.0,Manager,20993.0
1,200001,0,49.0,Company Invited,1,14.0,Salaried,Male,3,4.0,Deluxe,4.0,Divorced,2.0,0,3,1,2.0,Manager,20130.0
2,200002,1,37.0,Self Enquiry,1,8.0,Free Lancer,Male,3,4.0,Basic,3.0,Unmarried,7.0,1,3,0,0.0,Executive,17090.0
3,200003,0,33.0,Company Invited,1,9.0,Salaried,Female,2,3.0,Basic,3.0,Divorced,2.0,1,5,1,1.0,Executive,17909.0
4,200004,0,NaN,Self Enquiry,1,8.0,Small Business,Male,2,3.0,Basic,4.0,Divorced,1.0,0,5,1,0.0,Executive,18468.0

checking missing values

In [13]:
feature_with_na = [feature for feature in df.columns if df[feature].isnull().sum() >= 1]
for feature in feature_with_na:
    print(feature, np.round(df[feature].isnull().mean() * 100, 5), '% missing value')

Age 4.62357 % missing value
TypeofContact 0.51146 % missing value
DurationOfPitch 5.13502 % missing value
NumberOfFollowups 0.92062 % missing value
PreferredPropertyStar 0.53191 % missing value
NumberOfTrips 2.86416 % missing value
NumberOfChildrenVisiting 1.35025 % missing value
MonthlyIncome 4.76678 % missing value

# Imputing null values 

 # 1- Median value  for age column
of the column is used to impute the null values. Median is the middle value of a data

# 2 - Mode for type of contact

In [14]:
df.Age.fillna(df.Age.median() , inplace=True )

df.TypeofContact.fillna(df.TypeofContact.mode()[0] , inplace=True)

df.DurationOfPitch.fillna(df.DurationOfPitch.median() , inplace=True)

df.NumberOfFollowups.fillna(df.NumberOfFollowups.mode()[0] , inplace=True)

df.PreferredPropertyStar.fillna(df.PreferredPropertyStar.mode()[0] , inplace= True)

df.NumberOfTrips.fillna(df.NumberOfTrips.median() , inplace= True)

df.NumberOfChildrenVisiting.fillna(df.NumberOfChildrenVisiting.mode()[0] , inplace= True)

df.MonthlyIncome.fillna(df.MonthlyIncome.median() , inplace= True)

C:\Users\aryan\AppData\Local\Temp\ipykernel_10924\2758189901.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df.Age.fillna(df.Age.median() , inplace=True )
C:\Users\aryan\AppData\Local\Temp\ipykernel_10924\2758189901.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df.TypeofContact.fillna(df.TypeofContact.mode()[0] , inplace=True)
C:\Users\aryan\AppData\Local\Temp\ipykernel_10924\2758189901.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df.DurationOfPitch.fillna(df.DurationOfPitch.median() , inplace=True)
C:\Users\aryan\AppData\Local\Temp\ipykernel_10924\2758189901.py:7: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df.NumberOfFollowups.fillna(df.NumberOfFollowups.mode()[0] , inplace=True)
C:\Users\aryan\AppData\Local\Temp\ipykernel_10924\2758189901.py:9: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df.PreferredPropertyStar.fillna(df.PreferredPropertyStar.mode()[0] , inplace= True)
C:\Users\aryan\AppData\Local\Temp\ipykernel_10924\2758189901.py:11: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df.NumberOfTrips.fillna(df.NumberOfTrips.median() , inplace= True)
C:\Users\aryan\AppData\Local\Temp\ipykernel_10924\2758189901.py:13: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df.NumberOfChildrenVisiting.fillna(df.NumberOfChildrenVisiting.mode()[0] , inplace= True)
C:\Users\aryan\AppData\Local\Temp\ipykernel_10924\2758189901.py:15: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df.MonthlyIncome.fillna(df.MonthlyIncome.median() , inplace= True)

In [15]:
df.head()

,CustomerID,ProdTaken,Age,TypeofContact,CityTier,DurationOfPitch,Occupation,Gender,NumberOfPersonVisiting,NumberOfFollowups,ProductPitched,PreferredPropertyStar,MaritalStatus,NumberOfTrips,Passport,PitchSatisfactionScore,OwnCar,NumberOfChildrenVisiting,Designation,MonthlyIncome
0,200000,1,41.0,Self Enquiry,3,6.0,Salaried,Female,3,3.0,Deluxe,3.0,Unmarried,1.0,1,2,1,0.0,Manager,20993.0
1,200001,0,49.0,Company Invited,1,14.0,Salaried,Male,3,4.0,Deluxe,4.0,Divorced,2.0,0,3,1,2.0,Manager,20130.0
2,200002,1,37.0,Self Enquiry,1,8.0,Free Lancer,Male,3,4.0,Basic,3.0,Unmarried,7.0,1,3,0,0.0,Executive,17090.0
3,200003,0,33.0,Company Invited,1,9.0,Salaried,Female,2,3.0,Basic,3.0,Divorced,2.0,1,5,1,1.0,Executive,17909.0
4,200004,0,36.0,Self Enquiry,1,8.0,Small Business,Male,2,3.0,Basic,4.0,Divorced,1.0,0,5,1,0.0,Executive,18468.0

In [16]:
df.isnull().sum()

CustomerID                  0
ProdTaken                   0
Age                         0
TypeofContact               0
CityTier                    0
DurationOfPitch             0
Occupation                  0
Gender                      0
NumberOfPersonVisiting      0
NumberOfFollowups           0
ProductPitched              0
PreferredPropertyStar       0
MaritalStatus               0
NumberOfTrips               0
Passport                    0
PitchSatisfactionScore      0
OwnCar                      0
NumberOfChildrenVisiting    0
Designation                 0
MonthlyIncome               0
dtype: int64

# feature engineering 

feature extraction

# creating new feature

In [17]:
df['TotalVisiting'] = df['NumberOfPersonVisiting'] + df['NumberOfChildrenVisiting']

In [18]:
df.drop(columns=['NumberOfPersonVisiting' , 'NumberOfChildrenVisiting'])

,CustomerID,ProdTaken,Age,TypeofContact,CityTier,DurationOfPitch,Occupation,Gender,NumberOfFollowups,ProductPitched,PreferredPropertyStar,MaritalStatus,NumberOfTrips,Passport,PitchSatisfactionScore,OwnCar,Designation,MonthlyIncome,TotalVisiting
0,200000,1,41.0,Self Enquiry,3,6.0,Salaried,Female,3.0,Deluxe,3.0,Unmarried,1.0,1,2,1,Manager,20993.0,3.0
1,200001,0,49.0,Company Invited,1,14.0,Salaried,Male,4.0,Deluxe,4.0,Divorced,2.0,0,3,1,Manager,20130.0,5.0
2,200002,1,37.0,Self Enquiry,1,8.0,Free Lancer,Male,4.0,Basic,3.0,Unmarried,7.0,1,3,0,Executive,17090.0,3.0
3,200003,0,33.0,Company Invited,1,9.0,Salaried,Female,3.0,Basic,3.0,Divorced,2.0,1,5,1,Executive,17909.0,3.0
4,200004,0,36.0,Self Enquiry,1,8.0,Small Business,Male,3.0,Basic,4.0,Divorced,1.0,0,5,1,Executive,18468.0,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4883,204883,1,49.0,Self Enquiry,3,9.0,Small Business,Male,5.0,Deluxe,4.0,Unmarried,2.0,1,1,1,Manager,26576.0,4.0
4884,204884,1,28.0,Company Invited,1,31.0,Salaried,Male,5.0,Basic,3.0,Unmarried,3.0,1,3,1,Executive,21212.0,6.0
4885,204885,1,52.0,Self Enquiry,3,17.0,Salaried,Female,4.0,Standard,4.0,Married,7.0,0,1,1,Senior Manager,31820.0,7.0
4886,204886,1,19.0,Self Enquiry,3,16.0,Small Business,Male,4.0,Basic,3.0,Unmarried,3.0,0,5,0,Executive,20289.0,5.0
4887,204887,1,36.0,Self Enquiry,1,14.0,Salaried,Male,4.0,Basic,4.0,Unmarried,3.0,1,3,1,Executive,24041.0,6.0

# get all numeric feature

In [19]:
num_feature = [feature for feature in df.columns if df[feature].dtype != 'o']
print('num of numeric Features : ' , len(num_feature))

num of numeric Features :  21

# categorical feature

In [20]:
cat_feature = [feature for feature in df.columns if df[feature].dtype == 'O']
print('num of categorical feature :' , len(cat_feature))

num of categorical feature : 6

# discreate feature

In [21]:
discrete_feature = [feature for feature in num_feature if len(df[feature].unique()) <= 25]
print('num of discrete feature:', len(discrete_feature))

num of discrete feature: 17

In [22]:
continuous_feature = [feature for feature in num_feature if feature not in discrete_feature]
print('num of continuous feature:', len(continuous_feature))

num of continuous feature: 4

# model training

In [23]:
from sklearn.model_selection import train_test_split

x = df.drop(['ProdTaken'], axis=1)
y = df['ProdTaken']

In [24]:
df.head()

,CustomerID,ProdTaken,Age,TypeofContact,CityTier,DurationOfPitch,Occupation,Gender,NumberOfPersonVisiting,NumberOfFollowups,...,PreferredPropertyStar,MaritalStatus,NumberOfTrips,Passport,PitchSatisfactionScore,OwnCar,NumberOfChildrenVisiting,Designation,MonthlyIncome,TotalVisiting
0,200000,1,41.0,Self Enquiry,3,6.0,Salaried,Female,3,3.0,...,3.0,Unmarried,1.0,1,2,1,0.0,Manager,20993.0,3.0
1,200001,0,49.0,Company Invited,1,14.0,Salaried,Male,3,4.0,...,4.0,Divorced,2.0,0,3,1,2.0,Manager,20130.0,5.0
2,200002,1,37.0,Self Enquiry,1,8.0,Free Lancer,Male,3,4.0,...,3.0,Unmarried,7.0,1,3,0,0.0,Executive,17090.0,3.0
3,200003,0,33.0,Company Invited,1,9.0,Salaried,Female,2,3.0,...,3.0,Divorced,2.0,1,5,1,1.0,Executive,17909.0,3.0
4,200004,0,36.0,Self Enquiry,1,8.0,Small Business,Male,2,3.0,...,4.0,Divorced,1.0,0,5,1,0.0,Executive,18468.0,2.0

In [25]:
y.value_counts()

ProdTaken
0    3968
1     920
Name: count, dtype: int64

In [26]:

from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=12)

In [27]:
x_train.shape , x_test.shape

((3910, 20), (978, 20))

# creating column transformer with 3 types of transformers

 onehotEncoder for categary data 

 StandardScaler for numeric data

In [28]:
cat_feature = x.select_dtypes(include='object').columns
num_feature = x.select_dtypes(exclude='object').columns

from sklearn.preprocessing import OneHotEncoder , StandardScaler
from sklearn.compose import ColumnTransformer

numeric_transformer = StandardScaler()
oh_transformer = OneHotEncoder(drop='first')

preprocessor = ColumnTransformer(
    [
        ("OneHotEncoder" , oh_transformer , cat_feature),
        ("StandardScaler" , numeric_transformer , num_feature)
    ]

)

# preprocessor is column tranformers

In [29]:
preprocessor

ColumnTransformer(transformers=[('OneHotEncoder', OneHotEncoder(drop='first'),
                                 Index(['TypeofContact', 'Occupation', 'Gender', 'ProductPitched',
       'MaritalStatus', 'Designation'],
      dtype='object')),
                                ('StandardScaler', StandardScaler(),
                                 Index(['CustomerID', 'Age', 'CityTier', 'DurationOfPitch',
       'NumberOfPersonVisiting', 'NumberOfFollowups', 'PreferredPropertyStar',
       'NumberOfTrips', 'Passport', 'PitchSatisfactionScore', 'OwnCar',
       'NumberOfChildrenVisiting', 'MonthlyIncome', 'TotalVisiting'],
      dtype='object'))])

In [30]:
x_train = preprocessor.fit_transform(x_train)
x_test = preprocessor.transform(x_test)

In [31]:
pd.DataFrame(x_train)

,0,1,2,3,4,5,6,7,8,9,...,19,20,21,22,23,24,25,26,27,28
0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,...,0.131960,0.288619,-0.723238,-0.131024,-0.648281,1.409654,-1.249230,-0.222777,0.269322,-0.066396
1,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.131960,0.288619,1.778186,-0.687875,-0.648281,1.409654,0.800493,-0.222777,0.974049,-0.066396
2,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,...,-1.251319,-0.715384,-0.723238,0.982678,-0.648281,-0.780154,-1.249230,-0.222777,1.854626,-0.777657
3,1.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.131960,1.292621,-0.723238,2.096380,1.542540,-1.510091,0.800493,0.957517,0.383833,0.644864
4,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,...,0.131960,-0.715384,1.778186,0.425827,1.542540,-1.510091,0.800493,-0.222777,2.120679,-0.066396
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3905,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,...,1.515239,1.292621,-0.723238,2.653231,1.542540,-0.050218,-1.249230,2.137810,-0.525229,2.067385
3906,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,...,-1.251319,-0.715384,-0.723238,-0.687875,-0.648281,-1.510091,-1.249230,-1.403070,-1.232424,-1.488918
3907,1.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.131960,2.296624,-0.723238,2.096380,-0.648281,-1.510091,0.800493,-0.222777,0.222796,-0.066396
3908,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.131960,0.288619,-0.723238,1.539529,1.542540,1.409654,0.800493,0.957517,0.027007,0.644864
3909,1.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,...,-1.251319,-0.715384,-0.723238,-0.131024,-0.648281,-0.050218,0.800493,-1.403070,0.018841,-1.488918

# Random forest classifier Training

#  this is efficient way to train model

In [32]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression

from sklearn.metrics import accuracy_score, precision_score , recall_score , f1_score , roc_auc_score

# training set performance

In [33]:
models = {
    'Logistic Regression': LogisticRegression(),
    'Random Forest': RandomForestClassifier(),
    'Decision Tree': DecisionTreeClassifier()
}

for i in range(len(list(models))):
    model_name = list(models.keys())[i]
    model = list(models.values())[i]
    model.fit(x_train, y_train)

    y_train_pred = model.predict(x_train)
    y_test_pred = model.predict(x_test)

    # training set performance 
    model_train_accuracy = accuracy_score(y_train, y_train_pred)
    model_train_f1 = f1_score(y_train, y_train_pred)
    model_train_presicion = precision_score(y_train, y_train_pred)
    model_train_recall = recall_score(y_train, y_train_pred)
    model_train_roc_auc_score = roc_auc_score(y_train, y_train_pred)

    # test set performance
    model_test_accuracy = accuracy_score(y_test, y_test_pred)
    model_test_f1 = f1_score(y_test, y_test_pred)
    model_test_presicion = precision_score(y_test, y_test_pred)
    model_test_recall = recall_score(y_test, y_test_pred)
    model_test_roc_auc_score = roc_auc_score(y_test, y_test_pred)


    print(model_name)
    print(' -------------------------')
    print(f"Training set accuracy: {model_train_accuracy:.2f}")
    print(f"Training set F1 score: {model_train_f1:.2f}")
    print(f"Training set precision: {model_train_presicion:.2f}")
    print(f"Training set recall: {model_train_recall:.2f}")
    print(f"Training set ROC AUC score: {model_train_roc_auc_score:.2f}")
    print('-----------------------------------------')
    print("Model Test Accuracy: ", model_test_accuracy)
    print(f"Test set F1 score: {model_test_f1:.2f}")
    print(f"Test set precision: {model_test_presicion:.2f}")
    print(f"Test set recall: {model_test_recall:.2f}")
    print(f"Test set ROC AUC score: {model_test_roc_auc_score:.2f}")
    print('='*35)
    print('\n')

Logistic Regression
 -------------------------
Training set accuracy: 0.84
Training set F1 score: 0.42
Training set precision: 0.70
Training set recall: 0.30
Training set ROC AUC score: 0.64
-----------------------------------------
Model Test Accuracy:  0.8404907975460123
Test set F1 score: 0.37
Test set precision: 0.70
Test set recall: 0.25
Test set ROC AUC score: 0.61
===================================


Random Forest
 -------------------------
Training set accuracy: 1.00
Training set F1 score: 1.00
Training set precision: 1.00
Training set recall: 1.00
Training set ROC AUC score: 1.00
-----------------------------------------
Model Test Accuracy:  0.9059304703476483
Test set F1 score: 0.68
Test set precision: 0.93
Test set recall: 0.53
Test set ROC AUC score: 0.76
===================================


Decision Tree
 -------------------------
Training set accuracy: 1.00
Training set F1 score: 1.00
Training set precision: 1.00
Training set recall: 1.00
Training set ROC AUC score: 1.00
-----------------------------------------
Model Test Accuracy:  0.8926380368098159
Test set F1 score: 0.71
Test set precision: 0.72
Test set recall: 0.70
Test set ROC AUC score: 0.82
===================================

# test set performance

In [34]:
model_test_accuracy = accuracy_score(y_test , y_test_pred)
print("Model Test Accuracy: ", model_test_accuracy)


model_train_f1 = f1_score(y_test , y_test_pred)
print(f"Training set F1 score: {model_train_f1:.2f}")

model_train_presicion = precision_score(y_test , y_test_pred)
print(f"Training set precision: {model_train_presicion:.2f}")

model_train_recall = recall_score(y_test , y_test_pred)
print(f"Training set recall: {model_train_recall:.2f}")

model_train_roc_auc_score = roc_auc_score(y_test , y_test_pred)
print(f"Training set ROC AUC score: {model_train_roc_auc_score:.2f}")

Model Test Accuracy:  0.8926380368098159
Training set F1 score: 0.71
Training set precision: 0.72
Training set recall: 0.70
Training set ROC AUC score: 0.82

# Random Forest Classifier Training

In [35]:
from sklearn.ensemble import RandomForestClassifier

from sklearn.tree import DecisionTreeClassifier

from sklearn.svm import SVC

from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import GradientBoostingClassifier, AdaBoostClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix, precision_score , recall_score , f1_score , roc_auc_score, roc_curve

In [36]:


models = {
    'Random Forest': RandomForestClassifier(),
    'Support Vector Machine': SVC(),
    'Decision Tree': DecisionTreeClassifier(),
    'Logistic Regression': LogisticRegression(),
    'Gradient Boosting': GradientBoostingClassifier(),
    'Adaboost':AdaBoostClassifier()

}

for i in range(len(list(models))):
    model = list(models.values())[i]

    model.fit(x_train, y_train)

    y_train_pred=model.predict(x_train)
    y_test_pred=model.predict(x_test)


    # trianining performance

    print(list(models.keys())[i])

    model_train_accuracy = accuracy_score(y_train, y_train_pred)
    model_train_f1 = f1_score(y_train, y_train_pred)
    model_train_presicion = precision_score(y_train, y_train_pred)
    model_train_recall = recall_score(y_train, y_train_pred)
    model_train_roc_auc_score = roc_auc_score(y_train, y_train_pred)

    # test set performance
    model_test_accuracy = accuracy_score(y_test, y_test_pred)
    model_test_f1 = f1_score(y_test, y_test_pred)
    model_test_presicion = precision_score(y_test, y_test_pred)
    model_test_recall = recall_score(y_test, y_test_pred)
    model_test_roc_auc_score = roc_auc_score(y_test, y_test_pred)



    print(' -------------------------')
    print(f"Training set accuracy: {model_train_accuracy:.2f}")
    print(f"Training set F1 score: {model_train_f1:.2f}")
    print(f"Training set precision: {model_train_presicion:.2f}")
    print(f"Training set recall: {model_train_recall:.2f}")
    print(f"Training set ROC AUC score: {model_train_roc_auc_score:.2f}")
    print('-----------------------------------------')
    print("Model Test Accuracy: ", model_test_accuracy)
    print(f"Test set F1 score: {model_test_f1:.2f}")
    print(f"Test set precision: {model_test_presicion:.2f}")
    print(f"Test set recall: {model_test_recall:.2f}")
    print(f"Test set ROC AUC score: {model_test_roc_auc_score:.2f}")
    print('='*35)
    print('\n')

Random Forest
 -------------------------
Training set accuracy: 1.00
Training set F1 score: 1.00
Training set precision: 1.00
Training set recall: 1.00
Training set ROC AUC score: 1.00
-----------------------------------------
Model Test Accuracy:  0.9028629856850716
Test set F1 score: 0.66
Test set precision: 0.94
Test set recall: 0.51
Test set ROC AUC score: 0.75
===================================


Support Vector Machine
 -------------------------
Training set accuracy: 0.89
Training set F1 score: 0.61
Training set precision: 0.92
Training set recall: 0.45
Training set ROC AUC score: 0.72
-----------------------------------------
Model Test Accuracy:  0.852760736196319
Test set F1 score: 0.41
Test set precision: 0.80
Test set recall: 0.28
Test set ROC AUC score: 0.63
===================================


Decision Tree
 -------------------------
Training set accuracy: 1.00
Training set F1 score: 1.00
Training set precision: 1.00
Training set recall: 1.00
Training set ROC AUC score: 1.00
-----------------------------------------
Model Test Accuracy:  0.8885480572597138
Test set F1 score: 0.70
Test set precision: 0.70
Test set recall: 0.69
Test set ROC AUC score: 0.81
===================================


Logistic Regression
 -------------------------
Training set accuracy: 0.84
Training set F1 score: 0.42
Training set precision: 0.70
Training set recall: 0.30
Training set ROC AUC score: 0.64
-----------------------------------------
Model Test Accuracy:  0.8404907975460123
Test set F1 score: 0.37
Test set precision: 0.70
Test set recall: 0.25
Test set ROC AUC score: 0.61
===================================


Gradient Boosting
 -------------------------
Training set accuracy: 0.89
Training set F1 score: 0.63
Training set precision: 0.89
Training set recall: 0.49
Training set ROC AUC score: 0.74
-----------------------------------------
Model Test Accuracy:  0.8640081799591002
Test set F1 score: 0.50
Test set precision: 0.79
Test set recall: 0.37
Test set ROC AUC score: 0.67
===================================


Adaboost
 -------------------------
Training set accuracy: 0.85
Training set F1 score: 0.39
Training set precision: 0.82
Training set recall: 0.26
Training set ROC AUC score: 0.62
-----------------------------------------
Model Test Accuracy:  0.8496932515337423
Test set F1 score: 0.35
Test set precision: 0.89
Test set recall: 0.22
Test set ROC AUC score: 0.61
===================================

# ⚙️ Benefits of Hyperparameter Tuning
Improved Model Performance: Optimal hyperparameters can significantly boost a model's predictive capabilities. 
GeeksforGeeks

Reduced Overfitting and Underfitting: Tuning helps in achieving a model that neither overfits nor underfits the data.

Enhanced Generalization: Models with well-tuned hyperparameters perform better on new, unseen data. 
futuremachinelearning.org
+3
Applied AI Course
+3
O'Reilly
+3

Efficient Training: Proper hyperparameter settings can lead to faster convergence during training.

# hyperparameter testing why uses

1. Enhances Model Performance

Tuning hyperparameters can significantly improve a model's predictive accuracy. By finding the optimal combination of hyperparameters, models can achieve better performance on both training and unseen data.


2. Balances Bias and Variance

Proper hyperparameter tuning helps in finding the right balance between underfitting (high bias) and overfitting (high variance). This balance ensures that the model generalizes well to new data.

In [37]:
rf_params = {
    'max_depth':[5,8,14,11],
    'max_features':[5,7,"auto",8],
    'min_sample_split':[2,8,15,20],
    'n_estimators':[100,200,500,1000]
}

In [38]:
rf_params

{'max_depth': [5, 8, 14, 11],
 'max_features': [5, 7, 'auto', 8],
 'min_sample_split': [2, 8, 15, 20],
 'n_estimators': [100, 200, 500, 1000]}

In [39]:
randomcv_models = [
    ("RF", RandomForestClassifier() , rf_params),
]

In [40]:
from sklearn.model_selection import RandomizedSearchCV

model_params = {}

for name, estimator, params in randomcv_models:
    random = RandomizedSearchCV(
        estimator=estimator,
        param_distributions=params,
        n_iter=100,
        cv=3,
        verbose=3,
        n_jobs=-1
    )
    random.fit(x_train, y_train)
    model_params[name] = random.best_params_

    print(f"--------- Best Parameters for {name} : {model_params[name]} -----------")
    print(model_params[name])

Fitting 3 folds for each of 100 candidates, totalling 300 fits

ValueError: Invalid parameter 'min_sample_split' for estimator RandomForestClassifier(). Valid parameters are: ['bootstrap', 'ccp_alpha', 'class_weight', 'criterion', 'max_depth', 'max_features', 'max_leaf_nodes', 'max_samples', 'min_impurity_decrease', 'min_samples_leaf', 'min_samples_split', 'min_weight_fraction_leaf', 'monotonic_cst', 'n_estimators', 'n_jobs', 'oob_score', 'random_state', 'verbose', 'warm_start'].

In [ ]:
from sklearn.ensemble import RandomForestClassifier

In [ ]:
models = {
    'Random Forest': RandomForestClassifier(n_estimators=1000, min_samples_split=2,
                                            max_features=7, max_depth=None)
}
for i in range(len(list(models))):
    model = list(models.values())[i]
    model.fit(x_train, y_train)

    x_train_pred = model.predict(x_train)
    x_test_pred = model.predict(x_test)


    

    model_train_accuracy = accuracy_score(y_train, y_train_pred)
    model_train_f1 = f1_score(y_train, y_train_pred)
    model_train_presicion = precision_score(y_train, y_train_pred)
    model_train_recall = recall_score(y_train, y_train_pred)
    model_train_roc_auc_score = roc_auc_score(y_train, y_train_pred)

    # test set performance
    model_test_accuracy = accuracy_score(y_test, y_test_pred)
    model_test_f1 = f1_score(y_test, y_test_pred)
    model_test_presicion = precision_score(y_test, y_test_pred)
    model_test_recall = recall_score(y_test, y_test_pred)
    model_test_roc_auc_score = roc_auc_score(y_test, y_test_pred)



    print(' -------------------------')
    print(f"Training set accuracy: {model_train_accuracy:.2f}")
    print(f"Training set F1 score: {model_train_f1:.2f}")
    print(f"Training set precision: {model_train_presicion:.2f}")
    print(f"Training set recall: {model_train_recall:.2f}")
    print(f"Training set ROC AUC score: {model_train_roc_auc_score:.2f}")
    print('-----------------------------------------')
    print("Model Test Accuracy: ", model_test_accuracy)
    print(f"Test set F1 score: {model_test_f1:.2f}")
    print(f"Test set precision: {model_test_presicion:.2f}")
    print(f"Test set recall: {model_test_recall:.2f}")
    print(f"Test set ROC AUC score: {model_test_roc_auc_score:.2f}")
    print('='*35)
    print('\n')

# plot ROC AUC Curve

In [ ]:
from sklearn.metrics import roc_auc_score , roc_curve
plt.figure()

auc_models =[
    {
        'label': 'RandomForestClassifier',
        'model': RandomForestClassifier(n_estimators=1000, min_samples_split=2,
                                            max_features=7, max_depth=None),

        'auc':0.8319
    }
]

In [ ]:
# create a loop through all models

for algo in auc_models:
    model = algo['model']
    model.fit(x_train, y_train)

    # Get predicted probabilities for the positive class
    y_proba = model.predict_proba(x_test)[:, 1]
    fpr, tpr, thresholds = roc_curve(y_test, y_proba)

    plt.plot(fpr, tpr, label='%s ROC (area = %0.2f)' % (algo['label'], algo['auc']))

    plt.plot([0, 1], [0, 1], 'r--')
    plt.xlim([0.0, 1.0])
    plt.ylim([0.0, 1.05])
    plt.xlabel('1-specificity false positive rate')
    plt.ylabel('sensitivity true positive rate')
    plt.title('receiver operating characteristic ')

    plt.legend(loc='lower right')
    plt.savefig('auc.png')
    plt.show()

# deploy

In [41]:
!pip install joblib

Requirement already satisfied: joblib in d:\b-tech cse iiit\b-tech cse iiit\machine_learning_project\travel\.venv\lib\site-packages (1.5.1)

In [42]:
import joblib

joblib.dump(model, 'rf_model.pkl')
joblib.dump(preprocessor, 'preprocessor.pkl')

['preprocessor.pkl']